### ISSUE TITLE
a crypto noob's question. how does edwards curve calculate inverse of a point?

### ISSUE THREAD

**Issue by expnkx** [floodyberry/ed25519-donna#37]
Does it use extended euclid or euler phi function?

**Comment by LoupVaillant** [comment]
The inverse of a *scalar*, you mean. Finding the inverse of a point, to the extent that would mean anything, means solving discrete logarithm. The security of the whole things hinges on the conjecture that we *cannot*, in practice, solve discrete logarithm.

And the answer is phi, because Euclid is not constant time.

**Comment by expnkx** [comment]
> The inverse of a _scalar_, you mean. Finding the inverse of a point, to the extent that would mean anything, means solving discrete logarithm. The security of the whole things hinges on the conjecture that we _cannot_, in practice, solve discrete logarithm.
> 
> And the answer is phi, because Euclid is not constant time.

What about RSA? Euclid or phi?

**Comment by noloader** [comment]
> What about RSA? Euclid or phi?

You should reserve bug reports for bugs in the project or library. It is usually considered rude to pollute the bug tracker with irrelevant chatter, like how do you use the library or how does something work.

Questions on usage or theory are better asked on a mailing list or one of the Stack Exchange sites. Maybe try https://crypto.stackexchange.com/ with your questions?
